{ pkgs }: {
    deps = [
      pkgs.vimPlugins.rust-tools-nvim
      pkgs.rust-motd
      pkgs.rust-code-analysis
      pkgs.rustypaste
      pkgs.rustc
      pkgs.rustcat
      pkgs.carnix
      pkgs.vimPlugins.rust-vim
      pkgs.rusty-man
      pkgs.haskellPackages.rustls
      pkgs.rustc-demangle
      pkgs.nodePackages.rust-analyzer-build-deps-../../applications/editors/vscode/extensions/rust-analyzer/build-deps
      pkgs.nodePackages_latest.rust-analyzer-build-deps-../../applications/editors/vscode/extensions/rust-analyzer/build-deps
      pkgs.rustfmt
      pkgs.rustscan
      pkgs.rusty-psn
      pkgs.rust-bindgen
      pkgs.matrix-synapse-tools.rust-synapse-compress-state
      pkgs.emacsPackages.rust-mode
      pkgs.rust-analyzer
      pkgs.rustup-toolchain-install-master
      pkgs.rust-petname
      pkgs.rustpython
      pkgs.rust-analyzer-unwrapped
      pkgs.rustdesk
      pkgs.rust-bindgen-unwrapped
      pkgs.rustic-rs
      pkgs.rust-script
      pkgs.rustup
      pkgs.rust-audit-info
      pkgs.rubyPackages_3_0.github-pages
      pkgs.haskellPackages.rasa-ext-logger
      pkgs.rPackages.pipe_design
      pkgs.rPackages.card
      pkgs.rPackages.mpr
      pkgs.rPackages.purging
      pkgs.rPackages.QGameTheory
      pkgs.rPackages.tutorial
      pkgs.rPackages.hthgu133aprobe
      pkgs.rPackages.APCtools
      pkgs.rPackages.dittodb
      pkgs.rPackages.reporter
      pkgs.rPackages.mrregression
      pkgs.emacsPackages.rvm
      pkgs.rPackages.SimCorrMix
      pkgs.rPackages.KBoost
      pkgs.rPackages.escape
      pkgs.rPackages.ems
      pkgs.rPackages.dagitty
      pkgs.rPackages.wheatprobe
      pkgs.rPackages.EDASeq
      pkgs.rPackages.waspr
      pkgs.rPackages.pd_mirna_1_0
      pkgs.rPackages.NeuroDecodeR
      pkgs.rPackages.populationPDXdesign
      pkgs.libretro.beetle-pcfx
      pkgs.rPackages.nspmix
      pkgs.haskellPackages.inspection-proxy
      pkgs.unifiedpush-common-proxies
      pkgs.libretro.beetle-psx-hw
      pkgs.vimPlugins.nvim-expand-expr
      pkgs.rPackages.unrepx
      pkgs.rPackages.NPMLEmix
      pkgs.gnomeExtensions.pnx-time-logger
      pkgs.ocamlPackages.ocsigen-ppx-rpc
      pkgs.libretro.beetle-psx
      pkgs.vimPlugins.ncm2-tagprefix
      pkgs.emacsPackages.nrepl-eval-sexp-fu
      pkgs.gnomeExtensions.pixel-saver
      pkgs.python310Packages.openpyxl
      pkgs.haskellPackages.non-empty-text
      pkgs.haskellPackages.network-packet-linux
      pkgs.python39Packages.openpyxl
      pkgs.notepad-next
      pkgs.nix-store-gcs-proxy
      pkgs.python39Packages.nbsphinx
      pkgs.python310Packages.nbsphinx
      pkgs.python39Packages.nose-pattern-exclude
      pkgs.python310Packages.nose-pattern-exclude
      pkgs.ncpamixer
      pkgs.rPackages.npExact
      pkgs.haskellPackages.network-protocol-xmpp
      pkgs.nntp-proxy
      pkgs.haskellPackages.np-extras
      pkgs.haskellPackages.api-opentheory-unicode
      pkgs.apio
      pkgs.haskellPackages.api-builder
      pkgs.haskellPackages.apiary-purescript
      pkgs.haskellPackages.api-maker
      pkgs.haskellPackages.api-tools
      pkgs.python310Packages.apipkg
      pkgs.emacsPackages.apib-mode
      pkgs.haskellPackages.apiary-helics
      pkgs.python310Packages.apispec
      pkgs.haskellPackages.apiary-http-client
      pkgs.python39Packages.apipkg
      pkgs.haskellPackages.api-rpc-accumulate
      pkgs.haskellPackages.api-yoti
      pkgs.python39Packages.apispec
      pkgs.haskellPackages.api-monobank
      pkgs.haskellPackages.apiary
      pkgs.haskellPackages.apiary-eventsource
      pkgs.haskellPackages.apiary-memcached
      pkgs.emacsPackages.apiwrap
      pkgs.haskellPackages.apiary-redis
      pkgs.haskellPackages.api-rpc-factom
      pkgs.haskellPackages.apiary-cookie
      pkgs.haskellPackages.apioiaf-client
      pkgs.haskellPackages.apiary-clientsession
      pkgs.haskellPackages.api-field-json-th
      pkgs.haskellPackages.apiary-persistent
      pkgs.haskellPackages.apiary-session
      pkgs.haskellPackages.api-rpc-pegnet
      pkgs.haskellPackages.apiary-authenticate
      pkgs.linuxPackages_hardened.sysdig
      pkgs.ispike
      pkgs.rPackages.AnnuityRIR
      pkgs.perl534Packages.DataUUID
      pkgs.python39Packages.python-rabbitair
      pkgs.perl534Packages.ListAllUtils
      pkgs.jdk18_headless
      pkgs.haskellPackages.dfsbuild
      pkgs.haskellPackages.cirru-parser
      pkgs.rPackages.polyCub
      pkgs.rPackages.alternativeSplicingEvents_hg38
      pkgs.gnome.gnome-boxes
      pkgs.python310Packages.ansi
      pkgs.haskellPackages.hsseccomp
      pkgs.haskellPackages.binance-exports
      pkgs.python39Packages.prance
      pkgs.kdf
      pkgs.haskellPackages.travis-meta-yaml
      pkgs.emacsPackages.diffsync
      pkgs.emacsPackages.auto-complete
      pkgs.python310Packages.pytest-metadata
      pkgs.vcluster
      pkgs.rPackages.mlr3db
      pkgs.xss-lock
      pkgs.octavePackages.io
      pkgs.log4jcheck
      pkgs.haskellPackages.patat
      pkgs.rPackages.galts
      pkgs.rPackages.RaggedExperiment
      pkgs.gnomeExtensions.undecorate
        pkgs.graalvm17-ce
        pkgs.maven
        pkgs.replitPackages.jdt-language-server
        pkgs.replitPackages.java-debug
    ];
}